### ISSUE TITLE
JOSS Review: Functionality

### ISSUE THREAD

**Issue by baperry2** [OpenTerrace/openterrace-python#167]
Installation
- [x] The installation instructions using pip should specify a required version of Python (instructions fail for 3.10 or less). In general, it might be helpful to note major dependencies/versions in the documentation and/or point users to the `pyproject.toml` file for more information on dependencies
- [x] editable installation instructions should tell users which steps can be skipped if they already have a conda installation

Functionality
- [x] GPU functionality is claimed, but no instructions are provided. I'd like to be able to run on GPU and CPU and see the performance difference (once my GPU machine is back online from maintenance)
- [x] The verification against an analytical solution included in the documentation is good. Can the ability to reproduce this be added to the github repo? Adding additional verification and validation showing the correct order of convergence and testing other functionality would strengthen the software, but is not blocking for acceptance. EDIT: actually now I see these are generated from the tests. Adding a bit more detail in the documentation to clarify this may be sufficient

Performance
- [x] “approaches the speed of compiled C or FORTRAN code” in the README is a performance claim, but can't really be verified. I'd recommend rephrasing this statement so it is not making a specific performance claim.

**Comment by jakobhaervig** [comment]
@baperry2, thanks for these comments.

Installation
- I now updated so that pyproject.toml and pypi explicitly states required Python version. Also, I pointed users to the pyproject.toml for all dependencies ([b00f8cb](https://github.com/OpenTerrace/openterrace-python/commit/b00f8cb88ab1cd88fa0c246a06a8af77017cd023))
- Installation guide now states which steps can be skipped if Conda is installed already (https://github.com/OpenTerrace/openterrace-python/commit/b00f8cb88ab1cd88fa0c246a06a8af77017cd023)

Functionality
- I removed support for GPU and updated documentation accordingly. I plan to look into this in future when time allows ([b00f8cb](https://github.com/OpenTerrace/openterrace-python/commit/b00f8cb88ab1cd88fa0c246a06a8af77017cd023))
- I added a note in the documentation, that the verification studies are based on a GitHub actions with a link ([b00f8cb](https://github.com/OpenTerrace/openterrace-python/commit/b00f8cb88ab1cd88fa0c246a06a8af77017cd023)).

Performance
- I performance claim is based on Numbas claim "Numba translates Python functions to optimized machine code at runtime using the industry-standard [LLVM](https://llvm.org/) compiler library. Numba-compiled numerical algorithms in Python can approach the speeds of C or FORTRAN." from https://numba.pydata.org/
To avoid confusion I've removed the claim.. ([b00f8cb](https://github.com/OpenTerrace/openterrace-python/commit/b00f8cb88ab1cd88fa0c246a06a8af77017cd023))

**Comment by baperry2** [comment]
Looks like my comments here have been sufficiently addressed.
